### ISSUE TITLE
bug(ui): wrong or missing text wrapping on excessive length inputs

### ISSUE THREAD

**Issue by jontmy** [AY2223S1-CS2103T-W10-4/tp#200]
Tracking issue for the issues with the following UI components:

- [ ] #191
- [ ] #185
- [ ] #183

**#191** and **#185**
![](https://raw.githubusercontent.com/ngquyduc/ped/main/files/80b1b19c-32b1-4066-84da-4fb3551913ea.png)

**#183**
![](https://raw.githubusercontent.com/kevinchangjk/ped/master/files/187413c7-5e62-4ba1-a2f7-01e9269d0fff.png)

**Comment by jontmy** [comment]
Not exactly sure whether we can fix these though:

>  Not allowed in v1.4:
adding/changing features
any UI changes (even purely cosmetic enhancements e.g., alignments, style changes are not allowed).

**Comment by domoberzin** [comment]
> Not exactly sure whether we can fix these though:
> 
> > Not allowed in v1.4:
> > adding/changing features
> > any UI changes (even purely cosmetic enhancements e.g., alignments, style changes are not allowed).

perhaps we can enforce a maximum length on arguments? Because I feel it would be relatively reasonable to believe that a user's input for the module name, task description, etc should not exceed 100 characters, for example. 

We could also further justify this in the UG/DG, because no amount of text wrapping is going to make an extremely long description nice and readable, and the user would either have to scroll a lot or we would need to dedicate a lot of GUI space for one task/module, which another user can also consider to be a bug.

**Comment by domoberzin** [comment]
Solution: Fix the wrapping and limit the description of tasks, and name of modules to 100 characters. @midnightfeverrr 
Module code and credit have been completed by @HoJunHao2000 in another PR.
